### ISSUE TITLE
lastal hits contain only /1 hits in --paired mode

### ISSUE THREAD

**Issue by koadman** [gjospin/PhyloSift#335]
When running on the grinder_illumina.fa test dataset and using --paired, the candidate files only contain sequence identifiers with /1. It seems that the /2 hits are disappearing somewhere along the way.

**Comment by gjospin** [comment]
should be fixed with commit 6124ed85f79710af0323bb3e14a05805065d07b2

**Comment by koadman** [comment]
I just checked my code and it has that change, sooo this is still a problem on devel.

**Comment by gjospin** [comment]
I have been able to replicate the issue.
After a quick investigation, it looks like demul_sequence does not print
the second read when --paired and there are not 2 input files.

I think a quick change from the FILEHANDLE check to the Array of values
check will fix the problem.

**Comment by gjospin** [comment]
fixed in commit cc8c1bea0c36ba44d7d40f5b37422ea0639c16e4
